Atendimento/urls.py
from django.urls import include, path

from . import views
from .views import (delete_paciente_a_triagem, envio_paciente_a_triagem,
                    lista_de_paciente_na_triagem, paciente_cadastro,
                    paciente_lista, Exibe_envios_data, Exibe_envios_data_atendimentos,
                    Exibe_documentos_paciente, ListagemPessoaBairroCidade)


app_name='Atendimento'

urlpatterns = [
    #Página Inicial
    path('resumo/', views.pagina_inicial, name='pagina-inicial'), 
    path('paciente/listagem', paciente_lista.as_view(), name='lista-paciente'),


    path('painel', views.painel, name='painel'), 
    path('painel_atendimento_Medico', views.chamar_paciente, name='chamar_paciente'),
    path('excluir-registros/', views.del_all_call, name='excluir_registros'),
    #path('painel_tiragem', views.chamar_paciente, name='chamar_paciente_triagem'),

    # Cadastro Etnia
    path('cadastro/sexo', views.Etnia_CreateView.as_view(), name='cadastra_etnia'),    

    # Cadastro Sexo
    path('cadastro/sexo', views.Sexo_CreateView.as_view(), name='cadastra_sexo'),    

    # Cadastro Pais
    path('cadastro/pais', views.Pais_CreateView.as_view(), name='cadastra_pais'),    

    # Cadastro Estado
    path('cadastro/estado', views.Estado_CreateView.as_view(), name='cadastra_estado'),    


    # Cadastro Cidade
    path('cadastro/cidade', views.Cidade_CreateView.as_view(), name='cadastra_cidade'),    

    # Cadastro Bairro
    path('cadastro/bairro', views.Bairro_CreateView.as_view(), name='cadastra_bairro'),    
    path('bairro/lista', views.Bairro_ListView.as_view(), name='list_bairro'),
    path('bairro/update/<int:pk>', views.Bairro_UpadateView.as_view(), name='Update_bairro'),
    path('bairro/deleta/<int:pk>', views.Bairro_Delete.as_view(), name='delete_bairro'),
    # Cadastro rua
    path('cadastro/Rua', views.Rua_CreateView.as_view(), name='cadastra_rua'),    
    path('Rua/lista', views.Rua_ListView.as_view(), name='list_rua'),
    path('Rua/update/<int:pk>', views.Rua_UpadateView.as_view(), name='Update_rua'),
    path('Rua/deleta/<int:pk>', views.Rua_Delete.as_view(), name='delete_rua'),
    

    path('paciente/listagem', paciente_lista.as_view(), name='lista-paciente'),
    path('paciente/registro', paciente_cadastro.as_view() , name='registro-paciente'),
    path('paciente/registro/<int:pk>', views.paciente_atualizar.as_view() , name='atualizar-paciente'),
    # Perfil do paciente
    path('paciente/perfil/<int:pk>', views.perfil_paciente, name='perfil-paciente'),
    path('paciente/perfil/historico/<int:pk>', views.perfil_paciente_hist, name='perfil-paciente-hist'),
    # FILA DE TRIAGEM    
    path('paciente/envio-paciente', envio_paciente_a_triagem.as_view(), name='envio_paciente_a_triagem'),    
    path('paciente/envio-paciente/<int:pk>', views.envio_paciente_a_triagem_2.as_view(), name='envio_paciente_a_triagem_2'),    
    path('paciente/triagem', views.lista_de_paciente_na_triagem, name='lista_de_paciente_na_triagem'),    
    path('paciente/triagem/<int:pk>', delete_paciente_a_triagem.as_view(), name='delete_de_paciente_na_triagem'),

    # Outras listagens
    path('pacient/envios_data', Exibe_envios_data.as_view(), name='listagem_envio' ),
    path('pacient/envios_data/atendimentos', Exibe_envios_data_atendimentos.as_view(), name='listagem_envio_atendimento' ),    
    path('pacient/envios_data/doucumentos_paciente', Exibe_documentos_paciente.as_view(), name='listagem_documentos_paciente' ),
    path('pacient/listagem/PessoaBairro', ListagemPessoaBairroCidade.as_view(), name='listagem_PessoaBairro' ),
     

]

upa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import path, re_path
from configUPA.views import handler404, handler500

from django.shortcuts import render  # Importe render

def handler500(request, *args, **kwargs):
    context = {'error_message': 'Oops! Houve um erro interno no servidor.'}
    return render(request, 'configUPA/error-500.html', context, status=500)


urlpatterns = [
    path('admin/', admin.site.urls),
    #Django_select2
    #Atendimento de emergencia
    path('', include('Access_Login.urls')),
    path('atendimento/', include('Atendimento.urls')),
    path('triagem/', include('Triagem.urls')),
    path('medicos/', include('Medicos.urls')),
    path('configura/', include('configUPA.urls')),
    path('imprime/', include('PrintPDFs.urls')),
    re_path(r'^.*/$', handler404),
    re_path(r'^.*/500/$', handler500),
]

handler500 = 'configUPA.views.handler500'

Atendimento/models.py
from datetime import date,timedelta, datetime
from django.db.models import Case, When, Value, BooleanField
from django.db import models
from django.db.models.signals import post_migrate
from django.dispatch import receiver


class Bairro (models.Model):
    bairro_nome = models.CharField(max_length=30)

    @receiver(post_migrate)
    def create_bairro(sender, **kwargs):
        bairro_nome = ['Aratuba', 'Baiacu', 'Barra do Gil', 'Barra do Pote', 'Berlinque', 'Cacha Pregos', 'Catu', 'Conceição', 'Coroa', 'Gameleira', 'Ilhota', 'Jiribatuba', 'Mar Grande', 'Ponta Grossa', 'Riachinho', 'Tairu']
    
        if not Bairro.objects.exists():
            for b in bairro_nome:
                Bairro.objects.create(
                    bairro_nome = b
                )

    def __str__(self):
        return self.bairro_nome
    
class Bairro_Vera_Cruz (models.Model):
    bairro_nome = models.CharField(max_length=30)

    @receiver(post_migrate)
    def create_bairro(sender, **kwargs):
        bairro_nome = ['Aratuba', 'Baiacu', 'Barra do Gil', 'Barra do Pote', 'Berlinque', 'Cacha Pregos', 'Catu', 'Conceição', 'Coroa', 'Gameleira', 'Ilhota', 'Jiribatuba', 'Mar Grande', 'Ponta Grossa', 'Riachinho', 'Tairu']
    
        if not Bairro.objects.exists():
            for b in bairro_nome:
                Bairro.objects.create(
                    bairro_nome = b
                )

    def __str__(self):
        return self.bairro_nome
    
        
class Rua(models.Model):
    rua_nome = models.CharField(max_length=100)

    @receiver(post_migrate)
    def create_rua(sender, **kwargs):
        rua_nome = ['Av. Ernesto Carneiro Ribeiro']
    
        if not Rua.objects.exists():
            for b in rua_nome:
                Rua.objects.create(
                    rua_nome = b
                )

    def __str__(self):
        return self.rua_nome
    

class Cidade(models.Model):
    cidade = models.CharField(max_length=100)

    @receiver(post_migrate)
    def create_cidade(sender, **kwargs):    
        if not Cidade.objects.exists():
            Cidade.objects.create(
                    cidade = "Vera Cruz"
                )

    def __str__(self):
        return self.cidade
    
    
class Estado(models.Model):
    estado = models.CharField(max_length=100)

    @receiver(post_migrate)
    def create_estado(sender, **kwargs):    
        if not Estado.objects.exists():
            Estado.objects.create(
                estado = 'Bahia'
            )

    def __str__(self):
        return self.estado
    

class Pais(models.Model):
    pais = models.CharField(max_length=100)

    @receiver(post_migrate)
    def create_pais(sender, **kwargs):    
        if not Pais.objects.exists():
            Pais.objects.create(
                pais = 'Brasil'
            )

    def __str__(self):
        return self.pais


class genero_sexual(models.Model):
    nome_genero = models.CharField(max_length=40, null=False, default='Outros')    

    @receiver(post_migrate)
    def create_genero_sexual(sender, **kwargs):
        #Irá pecorrer a lista de generos sexuais e adicionar conteudo nessa lista caso não exista
        nome_genero = ['Masculino', 'Feminino', 'Não-binário', 'Gênero fluido', 'Agênero', 'Dois-espíritos']
        if not genero_sexual.objects.exists():
            for gn in nome_genero:
                genero_sexual.objects.create(
                    nome_genero = gn
                    )
                print(f'generos: {nome_genero}')

    def __str__(self):
        return self.nome_genero
    

class Etnia(models.Model):
    etnia = models.CharField(max_length=40, null=False, default='Outros')    

    @receiver(post_migrate)
    def create_etnia(sender, **kwargs):
        #Irá pecorrer a lista de generos sexuais e adicionar conteudo nessa lista caso não exista
        etnia= ['Negro', 'Pardo', 'Branco']
        if not Etnia.objects.exists():
            for gn in etnia:
                Etnia.objects.create(
                    etnia = gn
                    )

    def __str__(self):
        return self.etnia

choices=(      
        ('0', 'Não'),
        ('1','Sim'),
    )
class ficha_de_atendimento(models.Model):
    nome_social = models.CharField(max_length=40, null=False, default='', verbose_name="Nome Social (Como a pessoa que ser chamada no painel)")
    nome_completo = models.CharField(max_length=50, null=True, default='', verbose_name="Nome completo (Como está escrito no RG)")
    codigo_pacient = models.CharField(max_length=8, null=True, verbose_name="Código do paciente")
    idade = models.IntegerField(null=False, default='00')    
    etnia = models.ForeignKey(Etnia, null=True, on_delete=models.CASCADE)
    data_nascimento = models.DateField( auto_now=False, auto_now_add=False, null=True, default='')
    sexo = models.ForeignKey(genero_sexual, null=True, on_delete=models.CASCADE)
    RG = models.CharField(max_length=13, null=True, default='')
    CPF = models.CharField(max_length=14, null=True, default='')
    nacionalidade = models.CharField(max_length=30, null=True, default='')
    rua = models.CharField(max_length=40, null=True, default='')
    bairro = models.ForeignKey(Bairro, on_delete=models.CASCADE, related_name='fichas_atendimento_bairro')
    cidade = models.ForeignKey(Cidade, null=True, on_delete=models.CASCADE)
    estado = models.ForeignKey(Estado, null=True, on_delete=models.CASCADE)
    pais = models.ForeignKey(Pais, on_delete=models.CASCADE, related_name='fichas_atendimento_pais')
    CEP = models.CharField(max_length=9, null=True, default='')
    nome_mae = models.CharField(max_length=40, null=True, default='')
    responsavel = models.CharField(max_length=30, null=True)
    tel = models.CharField(max_length=16, null=True, default='')
    data_cadastro = models.DateField(auto_now_add=True, null=False)
    data_update = models.DateField(auto_now=True, null=True)
    horario_cadastro = models.TimeField(null=True, auto_now_add=True)
    cartao_sus = models.CharField(max_length=15, null=True)
    ultimo_pk = None
    alergias = models.CharField(max_length=3, default='0', choices= choices, )
    conteudo_alergia = models.TextField(max_length=500, null=True, blank=True, default='Não possui alergias (Para tornar editável essa área, é necessário informar que o paciente possui alergias)')
    comorbidades = models.CharField(max_length=3, default='0', choices= choices )
    conteudo_comorbidades = models.TextField(max_length=500, null=True, blank=True, default='Não possui comobirdades (Para tornar editável essa área, é necessário informar que o paciente possui comobirdades)')
    nome_recepcionista = models.CharField(max_length=40, null=True, default='')
    
    class Meta:
        ordering = ['nome_social']          
    
    def save(self, *args, **kwargs):
        
        today = date.today()
        self.idade = today.year - self.data_nascimento.year - ((today.month, today.day) < (self.data_nascimento.month, self.data_nascimento.day))
        super().save(*args, **kwargs)
        return self.pk
        
    def __str__ (self):
        return f'Codigo: {self.codigo_pacient} | Nome Social: {self.nome_social} | Idade: {self.RG} anos | Idade: {self.idade} anos {"| ⚠️ Paciente Alergico " if not self.alergias else ""}'
    
    from datetime import datetime
    @receiver(post_migrate)
    def crie_registro(sender, **kwargs):
        paciente = ficha_de_atendimento.objects.filter(nome_social = "Enzzo Cauan Lins da Silva")
        paciente2 = ficha_de_atendimento.objects.filter(nome_social = "Bruna Cauanne Lins da Silva")
        paciente3 = ficha_de_atendimento.objects.filter(nome_social = "Cintia Teixeira Lins")
        paciente4 = ficha_de_atendimento.objects.filter(nome_social = "Vanda Paulino Cerqueira")
        paciente5 = ficha_de_atendimento.objects.filter(nome_social = "Rogério Cerqueira da Silva")
        paciente6 = ficha_de_atendimento.objects.filter(nome_social = "Rogerio Cerqueira da Silva")
        if not paciente:
            data_nasci = datetime.strptime('04/02/2013', "%d/%m/%Y")
            ficha_de_atendimento.objects.create(
                nome_social = 'Enzzo Cauan Lins da Silva',
                nome_completo = 'Enzzo Cauan Lins da Silva',
                nome_recepcionista = 'Dariuma',
                nome_mae = 'Cintia Teixeira Lins',
                data_nascimento = data_nasci,
                bairro = Bairro.objects.get(id=9),
                pais = Pais.objects.get(id=1)
            )
        if not paciente2:
            data_nasci = datetime.strptime('22/05/2005', "%d/%m/%Y")
            ficha_de_atendimento.objects.create(
                nome_social = 'Bruna Cauanne Lins da Silva',
                nome_completo = 'Bruna Cauanne Lins da Silva',
                nome_recepcionista = 'Dariuma',
                nome_mae = 'Cintia Teixeira Lins',
                data_nascimento = data_nasci,
                bairro = Bairro.objects.get(id=9),
                pais = Pais.objects.get(id=1)
            )
        if not paciente3:
            data_nasci = datetime.strptime('26/10/1988', "%d/%m/%Y")
            ficha_de_atendimento.objects.create(
                nome_social = "Cintia Teixeira Lins",
                nome_completo = 'Cintia Teixeira Lins',
                nome_recepcionista = 'Dariuma',
                nome_mae = 'Cintia Teixeira Lins',
                data_nascimento = data_nasci,
                bairro = Bairro.objects.get(id=9),
                pais = Pais.objects.get(id=1)
            )
        if not paciente4:
            data_nasci = datetime.strptime('26/10/1965', "%d/%m/%Y")
            ficha_de_atendimento.objects.create(
                nome_social = "Vanda Paulino Cerqueira",
                nome_completo = 'Vanda Paulino Cerqueira',
                nome_recepcionista = 'Dariuma',
                nome_mae = 'Alaíde',
                data_nascimento = data_nasci,
                bairro = Bairro.objects.get(id=9),

Atendimento/templates/Atendimento/partes_cadastro_pacientes/aviso_Limpa_formulario.html
<style>
    /* Estilos de modal simples para fins de demonstração */
    .modal {
        display: none;
        position: fixed;
        z-index: 1;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        overflow: auto;
        background-color: rgba(0,0,0,0.4);
    }

    .modal-content {
        background-color: #fefefe;
        margin: 15% auto;
        padding: 20px;
        border: 1px solid #888;
        width: 80%;
    }

    .modal-content button {
        margin: 5px;
    }
</style>

<!-- Modal -->
<div id="myModal" class="modal">
    <div class="modal-content">
        <h1 class="text-center h3">Olá {% if request.user.first_name  %}{{request.user.first_name}} {{request.user.last_name}} {% else %}<span class='text-capitalize'>{{request.user}}</span>{% endif %}! Deseja iniciar o formulário limpo ou com informações anteriores?</h1>
        <div class="d-flex justify-content-center">
            <button id="cleanFormBtn" class='btn btn-sm btn-primary' type='button'>Limpar Formulário</button>
            <button id="keepFormBtn" class='btn btn-sm btn-secondary'>Manter Informações Anteriores</button>
        </div>
    </div>
</div>
<script>
    // Função para esconder o modal
    function hideModal() {
        document.getElementById("myModal").style.display = "none";
    }

    // Função a ser executada quando o usuário escolher limpar o formulário
    function cleanForm() {
        // Lógica para limpar o formulário
        console.log("Formulário limpo!");
        hideModal();
    }

    // Função a ser executada quando o usuário escolher manter informações anteriores
    function keepForm() {
        // Lógica para manter as informações anteriores no formulário
        console.log("Manter informações anteriores!");
        hideModal();
    }

    // Adicionando eventos aos botões do modal
    document.getElementById("cleanFormBtn").addEventListener("click", cleanForm);
    document.getElementById("keepFormBtn").addEventListener("click", keepForm);

    // Mostrar o modal quando a página for carregada
    window.addEventListener('load', function() {
        document.getElementById("myModal").style.display = "block"; // Mostra o modal
    });
</script>

Atendimento/templates/Atendimento/partes_cadastro_pacientes/parte_form_cadastra_paciente.html
<div class="row row-cols-3 mb-5 p-3   g-4 justify-content-center">        
    {% csrf_token %}
    <!--  
    <div class="col-9 row row-cols-2 m-3 mx-0 p-3 bg-primary-subtle shadow shadow-sm " >
        <div class="col form-group">
            {{ form.nome_social.label_tag }}
            {{ form.nome_social }}
            {{ form.nome_social.errors }}
        </div>
        
        <div class="col form-group">
            {{ form.nome_completo.label_tag }}
            {{ form.nome_completo }}
            {{ form.nome_completo.errors }}
        </div>
       
    </div>  --> 
    <div class="col-4 form-group">
        {{ form.nome_social.label_tag }}
        {{ form.nome_social }}
        {{ form.nome_social.errors }}
    </div>            
    <div class=" col form-group">
        {{ form.codigo_pacient.label_tag }}
        {{ form.codigo_pacient }}
        {{ form.codigo_pacient.errors }}
    </div>
    <div class="col form-group">
        {{ form.data_nascimento.label_tag }}
        {{ form.data_nascimento }}
        {{ form.data_nascimento.errors }}
    </div>
    <div class="col form-group">
        {{ form.sexo.label_tag }}
        {{ form.sexo }}
        <p><a class="fa-sharp fa-solid fa-circle-plus rounded-5 shadow " title='Adicionar sexo' href="{% url 'Atendimento:cadastra_sexo' %}"></a></p>
        {{ form.sexo.errors }}
    </div>
    <div class="col form-group">
        {{ form.etnia.label_tag }}
        {{ form.etnia }}
        <p><a class="fa-sharp fa-solid fa-circle-plus rounded-5 shadow " title='Adicionar etnia' href="{% url 'Atendimento:cadastra_etnia' %}"></a></p>
        {{ form.etnia.errors }}
    </div>
    <div class="col form-group">
        {{ form.RG.label_tag }}
        {{ form.RG }}
        {{ form.RG.errors }}
    </div>
    <div class="col form-group">
        {{ form.CPF.label_tag }}
        {{ form.CPF }}
        {{ form.CPF.errors }}
    </div>
    <div class="col form-group">
        {{ form.nacionalidade.label_tag }}
        {{ form.nacionalidade }}
        {{ form.nacionalidade.errors }}
    </div>
    <div class="col form-group">
        {{ form.rua.label_tag }}
        {{ form.rua }}
        {{ form.rua.errors }}
    </div>
    <div class="col form-group">
        {{ form.bairro.label_tag }}
        {{ form.bairro }}
        <p><a class="fa-sharp fa-solid fa-circle-plus rounded-5 shadow " title='Adicionar bairro' href="{% url 'Atendimento:cadastra_bairro' %}"></a></p>
        {{ form.bairro.errors }}
    </div>
    <div class="col form-group">
        {{ form.cidade.label_tag }}
        {{ form.cidade }}
        <p><a class="fa-sharp fa-solid fa-circle-plus rounded-5 shadow " title='Adicionar cidade' href="{% url 'Atendimento:cadastra_cidade' %}"></a></p>
        {{ form.cidade.errors }}
    </div>
    <div class="col form-group">
        {{ form.estado.label_tag }}
        {{ form.estado }}
        <p><a class="fa-sharp fa-solid fa-circle-plus rounded-5 shadow " title='Adicionar estado' href="{% url 'Atendimento:cadastra_estado' %}"></a></p>
        {{ form.estado.errors }}
    </div>
    <div class="col form-group">
        {{ form.pais.label_tag }}
        {{ form.pais }}
        <p><a class="fa-sharp fa-solid fa-circle-plus rounded-5 shadow " title='Adicionar pais' href="{% url 'Atendimento:cadastra_pais' %}"></a></p>
        {{ form.pais.errors }}
    </div>
    <div class="col form-group">
        {{ form.CEP.label_tag }}
        {{ form.CEP }}
        {{ form.CEP.errors }}
    </div>
    <div class="col form-group">
        {{ form.nome_mae.label_tag }}
        {{ form.nome_mae }}
        {{ form.nome_mae.errors }}
    </div>
    <div class="col form-group">
        {{ form.tel.label_tag }}
        {{ form.tel }}
        {{ form.tel.errors }}
    </div>
    <div class="col form-group">
        {{ form.cartao_sus.label_tag }}
        {{ form.cartao_sus }}
        {{ form.cartao_sus.errors }}
    </div>       
</div>  
<div class="w-100 p-2 text-center row row-cols-2 gap-4 justify-content-center">
    <button type="reset" class='col-5 btn btn-sm btn-secondary' ><i class="fa-solid fa-broom"></i> Limpar o formulário</button>   
    <button class='col-5 btn btn-sm btn-primary' type="submit" onclick="limpaDados()"><i class="fa-solid fa-floppy-disk"></i> Salvar Registro</button>    
</div>
</form>