Medicos/urls.py
from django.urls import path, re_path

from . import views

app_name = 'Medicos'

urlpatterns = [
    path('', views.medico_protuario_view_, name='medico_prontuario'),
    #path('', views.medico_prontuario_view.as_view(), name='medico_prontuario'),
    path('atendimento/<int:pk>', views.medico_atendimento_view, name='medico_atendimento'), 
    # Chama Paciente
    path('iniciar-atendimento/<int:pk>/', views.iniciar_atendimento_view, name='iniciar_atendimento'),
    path('medico_chama_paciente/<int:pk>/', views.MedicoChamaPacienteView.as_view(), name='medico_chama_paciente'),
    path('enfermeira_chama_paciente/<int:pk>/', views.EnfermeiroChamaPacienteView.as_view(), name='enfermagem_chama_paciente'),
    path('medico_avisa_atendimentoo/<int:pk>/', views.chamar_pacientee.update_chama_paciente.Update_chama_usuarioo, name='medico_avisa_pacientee'),
    path('enfermagem_avisa_atendimentoo/<int:pk>/', views.Update_chama_usuario_triagem, name='enfermagem_avisa_pacientee'),
    path('medico_avisa_atendimentoo/<int:pk>/', views.Update_chama_usuario_pos_atendimento, name='medico_avisa_paciente_pos_atendimento'),

    #perfil completo do paciente / historico
    path('medico/lista_historico_paciente/', views.paciente_lista_historico.as_view(), name='lista_paciente_medico'),  
    path('medico/historico_paciente/<int:pk>', views.paciente_perfil_completo, name='perfil_completo_paciente'),  
    path('medico/historico_paciente_historico/<int:pk>', views.paciente_perfil_completo_segunda_parte, name='perfil_completo_segunda_parte'),  
    path('medico/historico_paciente/historico/<int:pk>', views.paciente_perfil_completo_menu_lateral, name='perfil_completo_paciente_menu_lateral'),
    
    path('atendimento/paciente/<int:pk>', views.atendimento_medico_createView.as_view(), name='dados do paciente'),
    path('atendimento/paciente/update/<int:pk>', views.atendimento_medico_Atualiza.as_view(), name='dados_do_paciente_atualiza'),
    path('atendimento/paciente/medicamento/<int:pk>', views.atendimento_medico_updateview.as_view(), name='dados_do_paciente_medicamentos'),
    path('atendimento_medico_concluido/<int:pk>', views.atendimento_medico_concluido_update.as_view(), name='final_medico_concluida'),
    path('atendimento_medico_concluido/exibe/<int:pk>', views.exibe_prescreve_medicamento_update.as_view(), name='exibe_prescreve_medicamento'),
    # PDFs ------------------------------------------------------------------
    path('atendimento_medico_concluido/exibe/geraPDF/<int:pk>', views.gerarPdf, name='geraPdf'),
    # Cria, atualiza e apaga ----------------------------------------------------------------------
    path('medico_signup/', views.medico_signup, name='medico_signup'),
    path('medico_signup/atulizando/<int:pk>', views.MedicoUpdateView.as_view(), name='medico_signup_atualiza'),
    path('medico_signup/atulizando/extras/<int:pk>', views.MedicoUpdateView_extra.as_view(), name='medico_signup_atualiza_extras'),
    path('medico_signup/delete/<int:pk>', views.MedicoDeleteView.as_view(), name='medico_delete'),
    # Salas
    path('medicos/cadastroSalas/', views.Cadastra_Sala_view.as_view(), name='cadastroSala' ),
    path('medicos/Salas/', views.Lista_Salas_ListView.as_view(), name='salas' ),    
    path('medicos/Salas/atualizacao/<int:pk>', views.Atualiza_Sala_UpdatView.as_view(), name='salasUpdate' ),
    path('medicos/Salas/delete/<int:pk>', views.Delete_Sala_Delet.as_view(), name='salasDelete' ),
    # Exames
    path('medicos/cadastroExames/', views.Cadastra_Exame_view.as_view(), name='cadastroExame' ),    
    path('medicos/cadastroExames/atualizacao/<int:pk>', views.Atualiza_Exame_UpdatView.as_view(), name='exameUpdate' ),
    path('medicos/Salas/', views.Lista_Salas_ListView.as_view(), name='salas' ),    
    path('medicos/Exames/delete/<int:pk>', views.Delete_Exame_Delet.as_view(), name='exameDelete' ),

    # Medicamentos
    path('medicos/cdastraMedicamento/', views.Cadastra_Medicamento.as_view(), name='cadastroMedicamento' ),    
    path('medicos/cadastroExames/atualizacao/<int:pk>', views.Atualiza_Exame_UpdatView.as_view(), name='exameUpdate' ),
    path('medicos/Salas/', views.Lista_Salas_ListView.as_view(), name='salas' ),    
    path('medicos/Exames/delete/<int:pk>', views.Delete_Exame_Delet.as_view(), name='exameDelete' ),
    # vincula Profissional
    path('medicos/Salas/profissional/', views.VinculaProfissiona_sala_view.as_view(), name='salasProfissionalCreate' ),
    path('medicos/Salas/profissional/update/<int:pk>', views.VinculaProfissiona_sala_update.as_view(), name='salasProfissionalUpdate' ),
    path('medicos/Salas/profissional/delete/<int:pk>', views.DeleteProfissionaSala_Delet.as_view(), name='salasProfissionalDelete' ),
  
    path('cadastrar-chamada/', views.cadastrar_chamada, name='cadastrar_chamada'),
    # importar csv para cid 10
    path('importar_csv/', views.import_csv, name='importa_csv'),
     # Paciente não atendeu ao chamdo
    path('medico/chama_paciente/n_atende/<int:pk>', views.medico_paciente_nao_atende, name='medio_n_atendeu'),
    # Conlclui todos atendimentos em aberto
    path('medico/chama_paciente/conclui_all/', views.conclui_all, name='conclui_atend'),
    # Atualizar o campo relatorio de Medico atendimento para True
    path('medico/imprime/<int:pk>', views.atualizar_relatorio, name='atualiza_relatorio')

]

Triagem/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import triagem_enfermaria, Classifica_risco_view, Classifica_risco_lista_view, Classifica_risco_Update_view, triagem_enfermariaUpdate, triagem_enfermaria_Alergia_Update, triagem_classifica_Risco_update, Triagem_Delete


app_name = 'Triagem'

urlpatterns = [
    path('', triagem_enfermaria.as_view(), name='triagem-enfermaria'),
    path('<int:pk>', triagem_enfermariaUpdate.as_view(), name='triagem-enfermaria-update'),    
    path(
    'alergias/<int:pk>/<str:hora>/<str:data>/<int:paciente_envio_triagem_id>/', 
    triagem_enfermaria_Alergia_Update.as_view(), 
    name='triagem-enfermaria-alergia-update'
),

    path('classifica_risco/<int:pk>', triagem_classifica_Risco_update.as_view(), name='triagem_classifica_Risco_update'),
    path('etiqueta/<int:pk>', views.EtiquetaView.as_view(), name='triagem_Etiqueta'),    
    # Atendimento especializado
    path('atend_especializado/', views.Atend_especializado_Create.as_view(), name='triagem_especializada'),    
    path('atend_especializado/List', views.Atend_especializado_LIstView.as_view(), name='triagem_especializada_ListView'),    
    path('atend_especializado/retorno/<int:pk>', views.Atend_especializado_UpdateView.as_view(), name='triagem_especializada_UpdateView'),
    path('triagem_concluida/<int:pk>', views.triagem_concluida_Update.as_view(), name='triagem_concluida'),
    path('triagem/delete/<int:pk>', Triagem_Delete.as_view(), name='triagem-delete'),

    # Classifica risco
    path('classifica-risco', Classifica_risco_view.as_view(), name='classifica-risco'),
    path('classifica-risco/lista', Classifica_risco_lista_view.as_view(), name='classifica-risco-lista'),   
    path('classifica-risco/update/<int:pk>', Classifica_risco_Update_view.as_view(), name='classifica-risco-Update'),   
    # cadastro de Enfermeras e Tec-enfermagem
    path('triagem/Enfermerios_e_Tec', views.Enferm_SignUpForm, name='user_create'),
    path('triagem/Enfermeros_e_Tec/atualiza/<int:pk>', views.EnfermUpdateView.as_view(), name='user_atualiza'),
    path('triagem/Enfermeros_e_Tec/deleta/<int:pk>', views.DeleteUserDelet.as_view(), name='user_delete'),
   
   # Paciente não atendeu ao chamdo
   path('triagem/chama_paciente/n_atende/<int:pk>', views.paciente_nao_atende, name='n_atendeu')
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

upa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import path, re_path
from configUPA.views import handler404, handler500

from django.shortcuts import render  # Importe render

def handler500(request, *args, **kwargs):
    context = {'error_message': 'Oops! Houve um erro interno no servidor.'}
    return render(request, 'configUPA/error-500.html', context, status=500)


urlpatterns = [
    path('admin/', admin.site.urls),
    #Django_select2
    #Atendimento de emergencia
    path('', include('Access_Login.urls')),
    path('atendimento/', include('Atendimento.urls')),
    path('triagem/', include('Triagem.urls')),
    path('medicos/', include('Medicos.urls')),
    path('configura/', include('configUPA.urls')),
    path('imprime/', include('PrintPDFs.urls')),
    re_path(r'^.*/$', handler404),
    re_path(r'^.*/500/$', handler500),
]

handler500 = 'configUPA.views.handler500'

Medicos/views/a_aguardando_atendimento.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from Atendimento.models import *
from Triagem.models import triagem
from django.contrib.auth.hashers import make_password
from Triagem.models import Atendimento_especializado
from Medicos.models import Medico_atendimento
from datetime import datetime


@login_required
def medico_protuario_view_(request):
    busca_paciente = request.GET.get('busca_paciente')
    nao_finalizado = []
    if busca_paciente:
        triagem_filtro = triagem.objects.exclude(final_medico_atendimento=1) and triagem.objects.filter(paciente_triagem__paciente_envio_triagem__nome_social__icontains = busca_paciente)    
        checked = 'checked'
    else:
        triagem_filtro = triagem.objects.exclude(final_medico_atendimento=1)
        checked = ''
    triage_all = triagem.objects.all()

    for ated_espec in triage_all:
        
        try:
            nao_finalizado.append(ated_espec.medico_atendimento.paciente_medico_atendimento.final_medico_atendimento)
            
        except Medico_atendimento.DoesNotExist:
            pass
    
    return render(request, 'Medicos/medico.html', {
        'object_list': triagem.objects.exclude(final_medico_atendimento=1),
        'atendimento_especi': Atendimento_especializado.objects.all(),
        'atendimentos_hoje': Medico_atendimento.objects.filter(data_medico=datetime.now()),
        'atend_aguarda_final': triagem_filtro,
        'checked5' : checked,
        'nao_finalizado': nao_finalizado,    
    })
    

Medicos/views/b_info_vindo_triagem.py
from django.contrib.auth.decorators import login_required
from Atendimento.models import *
from Triagem.models import triagem
from django.shortcuts import  render

@login_required
def medico_atendimento_view(request, pk):
    dados_triagem = triagem.objects.filter(pk=pk)
    for dados in dados_triagem:
        #tempo1 =datetime(dados.hora_triagem)
        dados = dados.paciente_triagem_id        
        dados_triagem = envio_triagem.objects.filter(pk=dados) 
        info_Hora_Tri = triagem.objects.filter(paciente_triagem_id=dados)
        for t in info_Hora_Tri:
            info_Hora_envioT = t.hora_triagem     

    dados_envio_triagem = envio_triagem.objects.filter(pk=dados)
    for dados in dados_envio_triagem:
        #tempo2 =time(dados.horario_triagem)
        dados = dados.paciente_envio_triagem_id 
        info_Hora_envioT = envio_triagem.objects.filter(paciente_envio_triagem_id = dados)
        for t in info_Hora_envioT:
            info_Hora_envioT = t.horario_triagem

    #contem o horário da triagem
    info_Hora_envioT

    #contem o horário do envio_triagem
    info_Hora_envioT   
        
    return render(request, 'Medicos/medico_atendimento.html', {
        'paciente_triagem' : triagem.objects.filter(pk=pk), 
        'ficha_atendimento' : ficha_de_atendimento.objects.filter(pk=dados),
        'dados_triagem' : dados_triagem,
        #'tempo' : tempo         
    } )

Medicos/views/c_Update_atendimento_Paciente.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.models import Group
from django.http import  HttpResponseRedirect
from django.urls import reverse
from django.views.generic import UpdateView
#from Medicos.forms import Form_medico_atendimento
from Medicos.models import CustomUser, Medico_atendimento
from Triagem.models import triagem
from Medicos.models import CustomUser


class atendimento_medico_Atualiza(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Medico_atendimento
    #Chave Estrangeira 'paciente_medico_atendimento'
    fields = ['paciente_medico_atendimento', 'historico_doenca_atual_HDA', 'exame_fisico', 'Diagnostico', 'conduta','classificacao_internacional_doenca_CID']
    template_name = 'Medicos/medico_atendimento_atendimento.html'   
    success_message = 'Avaliação médica feita com sucesso'
     
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) 
        pk = self.kwargs['pk']    
        trigem_id = Medico_atendimento.objects.get(pk=self.kwargs['pk'])        
        context['triagem'] = triagem.objects.filter(id = trigem_id.paciente_medico_atendimento.id)
        context['atendimento'] = 'atendimento'       

        return context
    
    #success_url = reverse_lazy('Medicos:dados do paciente_medicamentos self.kwargs['pk']')
    def get_success_url(self):
        return reverse('Medicos:dados_do_paciente_medicamentos', kwargs={'pk':self.object.paciente_medico_atendimento.id})
    
    
    

Medicos/views/c_atendimento_Paciente.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import Group
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.http import  HttpResponseRedirect
from django.urls import reverse
from django.views.generic import CreateView
from Medicos.models import CustomUser, Medico_atendimento, Chamar_P_para_atendimento
from Triagem.models import triagem
from datetime import datetime


class atendimento_medico_createView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Medico_atendimento
    #Chave Estrangeira 'paciente_medico_atendimento'
    fields = ['paciente_medico_atendimento', 'historico_doenca_atual_HDA', 'exame_fisico', 'Diagnostico','medicamento', 'conduta','classificacao_internacional_doenca_CID']
    template_name = 'Medicos/medico_atendimento_atendimento.html'   
    success_message = 'Avaliação médica feita com sucesso'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) 
        pk = self.kwargs['pk']  
    
        # Evitar Erros
        exibe_b = {}
        exibe_id = None
        try:
            # Usar o método first() para pegar o primeiro registro
            chamado = Chamar_P_para_atendimento.objects.filter(nome_paciente=pk, data_chamada__date=datetime.now().date()).first()
            exibe_b = chamado.chamado
            exibe_id = chamado.pk

        except AttributeError:
            messages.add_message(self.request, messages.DEBUG, f"Nenhuma chamada foi encontrada para o paciente {self.kwargs['pk']} na data de hoje")
     
        if exibe_b:
            pass
        else:
            chamado = False
            exibe_b = False
           
        context['triagem'] = triagem.objects.filter(id = pk)
        context['chamado'] = chamado
        context['exibe_b'] = exibe_b  
        context['atendimento'] = 'atendimento'     
        context['exibe_id'] = exibe_id              
        return context
    
    def form_valid(self, form):
        self.object = form.save(commit=False)
        
        # Define os campos do objeto Medico_atendimento
        self.object.paciente_medico_atendimento_id = self.kwargs['pk']        
        
        medico_id = self.request.user.id
        medico_group_id = None 
        medico_group = CustomUser.objects.filter(user_id=medico_id)
        
        for med in medico_group:
            medico_group_id = med.grupo_id
            crm = med.crm
            print(f'esse é o crm do medio {crm}{medico_group}')        
        medico_group = Group.objects.filter(id=medico_group_id)
        
        for med in medico_group:
            medico_group = med.name
            
            if medico_group == "group_Medicos":
                self.object.medico_nome = f'{self.request.user.first_name} {self.request.user.last_name} | CRM nº {crm}'
            else:
                self.object.medico_nome = self.request.user.username        
        self.object.paciente_medico_atendimento = True
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())
    
    def get_success_url(self):        
        return reverse('Medicos:dados_do_paciente_medicamentos', kwargs={'pk':self.kwargs['pk']})

Medicos/views/i_lista_paciente_busca.py
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from Atendimento.models import *


# lista de paciente e pesquisa com dados do historico
class paciente_lista_historico(LoginRequiredMixin, ListView):
    model = ficha_de_atendimento
    template_name = 'Medicos/perfis/pacientes.html'
    paginate_by = 10
    
    # Fazer a pesquisa
    def get_queryset(self):
        txt_nome = self.request.GET.get('busca-paciente')

        if txt_nome:
            nome = ficha_de_atendimento.objects.filter(nome_social__icontains = txt_nome) | ficha_de_atendimento.objects.filter(cartao_sus__icontains = txt_nome)
    
        else:
            nome = ficha_de_atendimento.objects.all()

        return nome

    def form_valid(self, form):  
        form.instance.usuario = self.request.user

        url = super().form_valid(form)
        return url

Medicos/templates/Medicos/exames/exames.html
{% extends 'global/template_geral.html' %}
{% block css %}
{% load static %}
<link rel="stylesheet" href="https://site-assets.fontawesome.com/releases/v6.5.0/css/sharp-light.css">
<link rel="stylesheet" href="{% static 'global/tabela/css/style.css' %}">
<style>
    .table{
        width: 95%;
        border-spacing: 0;
    }
    .table tr th{
       background-color:cadetblue;
    }

    .table tr th, .table tr td{
       text-align: center;
       border: 0.01rem solid rgb(204, 201, 201);
    }
    .delete{
        color: red;
        margin: 0.5rem;
    }
    .update{
        color: blue;
        margin: 0.5rem;    
    }

    /** FORM */
    .form {
        box-shadow: var(--shadow);
        padding: 0.5rem;
    }
    .form label{
        display: block;
        margin-top: 1rem;
    }
    .form input, .form textarea, .form select{
        margin-left: 0.2rem;
        border-radius: 0.8rem;
        padding: 0.5rem;
        border: 0.1rem solid coral;
        width: 90%;
        font-size: 1.1rem;
    }
</style>
{% endblock css %}  
<!--Imagem Representando o setor-->
{% block vetor-img-aereo %}<img src=" {% static 'home/doctor.fw.png' %} " alt="">{% endblock vetor-img-aereo %}
<!--END Imagem Representando o setor-->
{% block title_login %}ÁREA MÉDICA {% endblock title_login %}
{% block titulo_ %} ÁREA MÉDICA - Salas de Atendimento {% endblock titulo_ %} 
{% block body_title %}<i class="fa-duotone fa-house-medical-flag"></i> Dependências do Hospital {% endblock body_title %}
{% block body_login %}
    <!--Relação de Salas Cadastradas-->
<div class='row'>
    <div class='col bg-secondary-subtle mt--2 p-3'>
        {% if object_list %}
            {% if not vinculo_sala %}
                <h1 style="font-size: 1.8rem !important;"><i class="fa-thin fa-vial-circle-check"></i> Tipos de Exames</h1>
                <hr>  
                <!--Paginaçaõ da relação de salas -->
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-end">
                    {% if object_list.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{object_list.previous_page_number}}" aria-label="Previous">
                        <span aria-hidden="true">&laquo; Início</span>
                        </a>
                    </li>
                    {% endif %}
                    {% for page in object_list.paginator.page_range %}
                        {% if object_list.number|add:"-10" <= page <= object_list.number|add:"10" %}
                        <li class="page-item {% if page == object_list.number %}active{% endif %}">
                            <a class="page-link" href="?page={{ page }}">{{ page }}</a>
                        </li>
                        {% endif %}
                    {% endfor %}

                    {% if object_list.has_next %}  
                    <li class="page-item">
                        <a class="page-link" href="?page={{ object_list.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true"> &raquo;</span>
                        </a>
                    </li>
                    {% endif %}
                    </ul>
                </nav>            
                <table class="table table-sm table-striped" >
                    <tr class='fs-6'>
                        <th class='col-1'>id</th>
                        <th class='col-3'>SALA</th>
                        <th class='col-2'>AÇÃO</th>
                    </tr>
                    {% for list in object_list %} 
                    <tr>
                        <td>{{list.id}}</td>
                        <td>{{list.nome_exame}}</td>
                        <td><span><a href="{% url 'Medicos:exameUpdate' list.pk %}"><i class="fa-solid fa-pen-to-square update"></i></a></span> | <span><a href="{% url 'Medicos:exameDelete' list.pk %}"><i class="fa-solid fa-trash-can delete"></i></a></span></td>
                    </tr>
                    {% endfor %}
                </table>
            <!--FIM Paginaçaõ da relação de salas --> 
        {% endif %}        
    {% endif %}                 
        <!--Cadastro de Salas-->



    </div>
    <div class='col'>    
        {% if object_list %}
        {% if update %}                        
        <h1>Atualização de Exame</h1>  
        <hr> 
        {% elif salaProfissional %}
        <div class='p-4'>&nbsp;</div>
        <h1 class="fs-5 pt-5 uppercase"><i class="fa-duotone fa-house-medical-flag"></i> Vincular Profissional à Sala de Atendimento</h1>
        <div style='text-align: right; margin-right:5rem'>
            <a class="btn btn-sm btn-secondary m-3" href="{% url 'Medicos:cadastroSala' %}"><i class="fas fa-solid  fa-person-shelter"></i> Cadastro de Salas</a>        
        </div>
        {% elif DeleteVinculo %}
        <h2> Tem certeza que deseja deletar o VÍNCULO DO PROFISSIONAL à sala?</h2> 
        {% else %}
            
        {% if not conteudo == 'cadastraSala' %}
        <div class='mt-5'>&nbsp;</div>
        <h2 class='fs-4 text-center w-75 m-auto mt-5'> Tem certeza que deseja deletar o tipo de exame <b class='text-uppercase'>{{object}}</b>?</h2> 
        {% else %}
    
        <h1 class="h3 text-capitalize" style='margin-top:-2rem !important'> <i class="fa-thin fa-vial-circle-check"></i> Registrar novo tipo de exame</h1> 
        <hr>
        <div class='p-2 text-justify w-75' >

            Este formulário destina-se ao registro de um novo exame. Por favor, forneça as informações necessárias abaixo:
            <p class='pt-4'><strong>Nome do Exame:</strong></p>
            <div class='p-3'>
                <p>- Insira o nome completo ou a designação única do exame que está sendo registrado.</p>
                <p>- Ao preencher este formulário, certifique-se de fornecer um nome descritivo e exclusivo para o exame.</p>                
            </div>
        </div>
       
        {% endif %}
        {% endif %}
            
            <div>
                <form class='form' action="" method="post">
                    {% csrf_token %}
                    
                    {{form.as_div}}
                    <div class="grid row m-4">
                        <a class="col btn btn-sm btn-danger m-4 w-50 h-100" href="{%url 'Medicos:cadastroExame' %}">Cancelar</a> 
                        <button class="col btn btn-sm btn-primary m-4 w-50 h-100">
                            {% if update %}                        
                            Atualizar Salar
                            {% elif conteudo == 'cadastraSala' %}
                                Registrar novo exame <i class="fa-thin fa-vial-circle-check"></i>
                            {% else %}                            
                                {% if vinculo_sala %}
                                    Vincular o profissional à sala
                                    {% else %}
                                    Deletar {{nomeSala}}
                                {% endif %}

                            {% endif %} 
                            
                        </button>                  
                    </div>
                </form>
            </div>        
        {% endif %}   
    </div>
</div>
<div class='row'>
    <a class=' col btn btn-sm btn-secondary m-3' href="{% url 'Medicos:salasProfissionalCreate' %}"><i class="fa-solid fa-people-roof"></i> Vincula Profissional às Salas</a>    
    <a class=" col btn btn-sm btn-secondary m-3" href="{% url 'Medicos:cadastroSala' %}"><i class="fas fa-solid  fa-person-shelter"></i> Criar Salas</a>
    {% if grupo_usuario == 'group_UPA-Admin' or grupo_usuario == 'group_Enfermagem' %}     
    <a class="col fs-5 btn btn-sm bg-secondary-subtle m-3 w-50 border" href="{% url 'Triagem:triagem-enfermaria' %}"><i class="fa-sharp fa-thin fa-user-nurse-hair mr-5"></i><span class='pr-4 pl-4'> Ir para a Classificação </span><i class="fa-sharp fa-thin fa-user-nurse-hair-long"></i> </a>
    {% endif %}
    {% if  grupo_usuario == 'group_Medicos' or grupo_usuario == 'group_UPA-Admin' %}
    <a class="col fs-5 btn btn-sm bg-secondary-subtle m-3 w-50 border" href="{% url 'Medicos:medico_prontuario'  %}"><i class="fa-thin fa-user-doctor mr-5"></i><span class='pr-4 pl-4'> Ir para Atendimento Médico  </span><i class="fa-thin fa-user-doctor-hair-long"></i> </a>
    {% endif %}
</div>



{% endblock body_login %}