Atendimento/urls.py
from django.urls import include, path

from . import views
from .views import (delete_paciente_a_triagem, envio_paciente_a_triagem,
                    lista_de_paciente_na_triagem, paciente_cadastro,
                    paciente_lista, Exibe_envios_data, Exibe_envios_data_atendimentos,
                    Exibe_documentos_paciente, ListagemPessoaBairroCidade)


app_name='Atendimento'

urlpatterns = [
    #Página Inicial
    path('resumo/', views.pagina_inicial, name='pagina-inicial'), 
    path('paciente/listagem', paciente_lista.as_view(), name='lista-paciente'),


    path('painel', views.painel, name='painel'), 
    path('painel_atendimento_Medico', views.chamar_paciente, name='chamar_paciente'),
    path('excluir-registros/', views.del_all_call, name='excluir_registros'),
    #path('painel_tiragem', views.chamar_paciente, name='chamar_paciente_triagem'),

    # Cadastro Etnia
    path('cadastro/sexo', views.Etnia_CreateView.as_view(), name='cadastra_etnia'),    

    # Cadastro Sexo
    path('cadastro/sexo', views.Sexo_CreateView.as_view(), name='cadastra_sexo'),    

    # Cadastro Pais
    path('cadastro/pais', views.Pais_CreateView.as_view(), name='cadastra_pais'),    

    # Cadastro Estado
    path('cadastro/estado', views.Estado_CreateView.as_view(), name='cadastra_estado'),    


    # Cadastro Cidade
    path('cadastro/cidade', views.Cidade_CreateView.as_view(), name='cadastra_cidade'),    

    # Cadastro Bairro
    path('cadastro/bairro', views.Bairro_CreateView.as_view(), name='cadastra_bairro'),    
    path('bairro/lista', views.Bairro_ListView.as_view(), name='list_bairro'),
    path('bairro/update/<int:pk>', views.Bairro_UpadateView.as_view(), name='Update_bairro'),
    path('bairro/deleta/<int:pk>', views.Bairro_Delete.as_view(), name='delete_bairro'),
    # Cadastro rua
    path('cadastro/Rua', views.Rua_CreateView.as_view(), name='cadastra_rua'),    
    path('Rua/lista', views.Rua_ListView.as_view(), name='list_rua'),
    path('Rua/update/<int:pk>', views.Rua_UpadateView.as_view(), name='Update_rua'),
    path('Rua/deleta/<int:pk>', views.Rua_Delete.as_view(), name='delete_rua'),
    

    path('paciente/listagem', paciente_lista.as_view(), name='lista-paciente'),
    path('paciente/registro', paciente_cadastro.as_view() , name='registro-paciente'),
    path('paciente/registro/<int:pk>', views.paciente_atualizar.as_view() , name='atualizar-paciente'),
    # Perfil do paciente
    path('paciente/perfil/<int:pk>', views.perfil_paciente, name='perfil-paciente'),
    path('paciente/perfil/historico/<int:pk>', views.perfil_paciente_hist, name='perfil-paciente-hist'),
    # FILA DE TRIAGEM    
    path('paciente/envio-paciente', envio_paciente_a_triagem.as_view(), name='envio_paciente_a_triagem'),    
    path('paciente/envio-paciente/<int:pk>', views.envio_paciente_a_triagem_2.as_view(), name='envio_paciente_a_triagem_2'),    
    path('paciente/triagem', views.lista_de_paciente_na_triagem, name='lista_de_paciente_na_triagem'),    
    path('paciente/triagem/<int:pk>', delete_paciente_a_triagem.as_view(), name='delete_de_paciente_na_triagem'),

    # Outras listagens
    path('pacient/envios_data', Exibe_envios_data.as_view(), name='listagem_envio' ),
    path('pacient/envios_data/atendimentos', Exibe_envios_data_atendimentos.as_view(), name='listagem_envio_atendimento' ),    
    path('pacient/envios_data/doucumentos_paciente', Exibe_documentos_paciente.as_view(), name='listagem_documentos_paciente' ),
    path('pacient/listagem/PessoaBairro', ListagemPessoaBairroCidade.as_view(), name='listagem_PessoaBairro' ),
     

]

upa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import path, re_path
from configUPA.views import handler404, handler500

from django.shortcuts import render  # Importe render

def handler500(request, *args, **kwargs):
    context = {'error_message': 'Oops! Houve um erro interno no servidor.'}
    return render(request, 'configUPA/error-500.html', context, status=500)


urlpatterns = [
    path('admin/', admin.site.urls),
    #Django_select2
    #Atendimento de emergencia
    path('', include('Access_Login.urls')),
    path('atendimento/', include('Atendimento.urls')),
    path('triagem/', include('Triagem.urls')),
    path('medicos/', include('Medicos.urls')),
    path('configura/', include('configUPA.urls')),
    path('imprime/', include('PrintPDFs.urls')),
    re_path(r'^.*/$', handler404),
    re_path(r'^.*/500/$', handler500),
]

handler500 = 'configUPA.views.handler500'

Atendimento/models.py
from datetime import date,timedelta, datetime
from django.db.models import Case, When, Value, BooleanField
from django.db import models
from django.db.models.signals import post_migrate
from django.dispatch import receiver


class Bairro (models.Model):
    bairro_nome = models.CharField(max_length=30)

    @receiver(post_migrate)
    def create_bairro(sender, **kwargs):
        bairro_nome = ['Aratuba', 'Baiacu', 'Barra do Gil', 'Barra do Pote', 'Berlinque', 'Cacha Pregos', 'Catu', 'Conceição', 'Coroa', 'Gameleira', 'Ilhota', 'Jiribatuba', 'Mar Grande', 'Ponta Grossa', 'Riachinho', 'Tairu']
    
        if not Bairro.objects.exists():
            for b in bairro_nome:
                Bairro.objects.create(
                    bairro_nome = b
                )

    def __str__(self):
        return self.bairro_nome
    
class Bairro_Vera_Cruz (models.Model):
    bairro_nome = models.CharField(max_length=30)

    @receiver(post_migrate)
    def create_bairro(sender, **kwargs):
        bairro_nome = ['Aratuba', 'Baiacu', 'Barra do Gil', 'Barra do Pote', 'Berlinque', 'Cacha Pregos', 'Catu', 'Conceição', 'Coroa', 'Gameleira', 'Ilhota', 'Jiribatuba', 'Mar Grande', 'Ponta Grossa', 'Riachinho', 'Tairu']
    
        if not Bairro.objects.exists():
            for b in bairro_nome:
                Bairro.objects.create(
                    bairro_nome = b
                )

    def __str__(self):
        return self.bairro_nome
    
        
class Rua(models.Model):
    rua_nome = models.CharField(max_length=100)

    @receiver(post_migrate)
    def create_rua(sender, **kwargs):
        rua_nome = ['Av. Ernesto Carneiro Ribeiro']
    
        if not Rua.objects.exists():
            for b in rua_nome:
                Rua.objects.create(
                    rua_nome = b
                )

    def __str__(self):
        return self.rua_nome
    

class Cidade(models.Model):
    cidade = models.CharField(max_length=100)

    @receiver(post_migrate)
    def create_cidade(sender, **kwargs):    
        if not Cidade.objects.exists():
            Cidade.objects.create(
                    cidade = "Vera Cruz"
                )

    def __str__(self):
        return self.cidade
    
    
class Estado(models.Model):
    estado = models.CharField(max_length=100)

    @receiver(post_migrate)
    def create_estado(sender, **kwargs):    
        if not Estado.objects.exists():
            Estado.objects.create(
                estado = 'Bahia'
            )

    def __str__(self):
        return self.estado
    

class Pais(models.Model):
    pais = models.CharField(max_length=100)

    @receiver(post_migrate)
    def create_pais(sender, **kwargs):    
        if not Pais.objects.exists():
            Pais.objects.create(
                pais = 'Brasil'
            )

    def __str__(self):
        return self.pais


class genero_sexual(models.Model):
    nome_genero = models.CharField(max_length=40, null=False, default='Outros')    

    @receiver(post_migrate)
    def create_genero_sexual(sender, **kwargs):
        #Irá pecorrer a lista de generos sexuais e adicionar conteudo nessa lista caso não exista
        nome_genero = ['Masculino', 'Feminino', 'Não-binário', 'Gênero fluido', 'Agênero', 'Dois-espíritos']
        if not genero_sexual.objects.exists():
            for gn in nome_genero:
                genero_sexual.objects.create(
                    nome_genero = gn
                    )
                print(f'generos: {nome_genero}')

    def __str__(self):
        return self.nome_genero
    

class Etnia(models.Model):
    etnia = models.CharField(max_length=40, null=False, default='Outros')    

    @receiver(post_migrate)
    def create_etnia(sender, **kwargs):
        #Irá pecorrer a lista de generos sexuais e adicionar conteudo nessa lista caso não exista
        etnia= ['Negro', 'Pardo', 'Branco']
        if not Etnia.objects.exists():
            for gn in etnia:
                Etnia.objects.create(
                    etnia = gn
                    )

    def __str__(self):
        return self.etnia

choices=(      
        ('0', 'Não'),
        ('1','Sim'),
    )
class ficha_de_atendimento(models.Model):
    nome_social = models.CharField(max_length=40, null=False, default='', verbose_name="Nome Social (Como a pessoa que ser chamada no painel)")
    nome_completo = models.CharField(max_length=50, null=True, default='', verbose_name="Nome completo (Como está escrito no RG)")
    codigo_pacient = models.CharField(max_length=8, null=True, verbose_name="Código do paciente")
    idade = models.IntegerField(null=False, default='00')    
    etnia = models.ForeignKey(Etnia, null=True, on_delete=models.CASCADE)
    data_nascimento = models.DateField( auto_now=False, auto_now_add=False, null=True, default='')
    sexo = models.ForeignKey(genero_sexual, null=True, on_delete=models.CASCADE)
    RG = models.CharField(max_length=13, null=True, default='')
    CPF = models.CharField(max_length=14, null=True, default='')
    nacionalidade = models.CharField(max_length=30, null=True, default='')
    rua = models.CharField(max_length=40, null=True, default='')
    bairro = models.ForeignKey(Bairro, on_delete=models.CASCADE, related_name='fichas_atendimento_bairro')
    cidade = models.ForeignKey(Cidade, null=True, on_delete=models.CASCADE)
    estado = models.ForeignKey(Estado, null=True, on_delete=models.CASCADE)
    pais = models.ForeignKey(Pais, on_delete=models.CASCADE, related_name='fichas_atendimento_pais')
    CEP = models.CharField(max_length=9, null=True, default='')
    nome_mae = models.CharField(max_length=40, null=True, default='')
    responsavel = models.CharField(max_length=30, null=True)
    tel = models.CharField(max_length=16, null=True, default='')
    data_cadastro = models.DateField(auto_now_add=True, null=False)
    data_update = models.DateField(auto_now=True, null=True)
    horario_cadastro = models.TimeField(null=True, auto_now_add=True)
    cartao_sus = models.CharField(max_length=15, null=True)
    ultimo_pk = None
    alergias = models.CharField(max_length=3, default='0', choices= choices, )
    conteudo_alergia = models.TextField(max_length=500, null=True, blank=True, default='Não possui alergias (Para tornar editável essa área, é necessário informar que o paciente possui alergias)')
    comorbidades = models.CharField(max_length=3, default='0', choices= choices )
    conteudo_comorbidades = models.TextField(max_length=500, null=True, blank=True, default='Não possui comobirdades (Para tornar editável essa área, é necessário informar que o paciente possui comobirdades)')
    nome_recepcionista = models.CharField(max_length=40, null=True, default='')
    
    class Meta:
        ordering = ['nome_social']          
    
    def save(self, *args, **kwargs):
        
        today = date.today()
        self.idade = today.year - self.data_nascimento.year - ((today.month, today.day) < (self.data_nascimento.month, self.data_nascimento.day))
        super().save(*args, **kwargs)
        return self.pk
        
    def __str__ (self):
        return f'Codigo: {self.codigo_pacient} | Nome Social: {self.nome_social} | Idade: {self.RG} anos | Idade: {self.idade} anos {"| ⚠️ Paciente Alergico " if not self.alergias else ""}'
    
    from datetime import datetime
    @receiver(post_migrate)
    def crie_registro(sender, **kwargs):
        paciente = ficha_de_atendimento.objects.filter(nome_social = "Enzzo Cauan Lins da Silva")
        paciente2 = ficha_de_atendimento.objects.filter(nome_social = "Bruna Cauanne Lins da Silva")
        paciente3 = ficha_de_atendimento.objects.filter(nome_social = "Cintia Teixeira Lins")
        paciente4 = ficha_de_atendimento.objects.filter(nome_social = "Vanda Paulino Cerqueira")
        paciente5 = ficha_de_atendimento.objects.filter(nome_social = "Rogério Cerqueira da Silva")
        paciente6 = ficha_de_atendimento.objects.filter(nome_social = "Rogerio Cerqueira da Silva")
        if not paciente:
            data_nasci = datetime.strptime('04/02/2013', "%d/%m/%Y")
            ficha_de_atendimento.objects.create(
                nome_social = 'Enzzo Cauan Lins da Silva',
                nome_completo = 'Enzzo Cauan Lins da Silva',
                nome_recepcionista = 'Dariuma',
                nome_mae = 'Cintia Teixeira Lins',
                data_nascimento = data_nasci,
                bairro = Bairro.objects.get(id=9),
                pais = Pais.objects.get(id=1)
            )
        if not paciente2:
            data_nasci = datetime.strptime('22/05/2005', "%d/%m/%Y")
            ficha_de_atendimento.objects.create(
                nome_social = 'Bruna Cauanne Lins da Silva',
                nome_completo = 'Bruna Cauanne Lins da Silva',
                nome_recepcionista = 'Dariuma',
                nome_mae = 'Cintia Teixeira Lins',
                data_nascimento = data_nasci,
                bairro = Bairro.objects.get(id=9),
                pais = Pais.objects.get(id=1)
            )
        if not paciente3:
            data_nasci = datetime.strptime('26/10/1988', "%d/%m/%Y")
            ficha_de_atendimento.objects.create(
                nome_social = "Cintia Teixeira Lins",
                nome_completo = 'Cintia Teixeira Lins',
                nome_recepcionista = 'Dariuma',
                nome_mae = 'Cintia Teixeira Lins',
                data_nascimento = data_nasci,
                bairro = Bairro.objects.get(id=9),
                pais = Pais.objects.get(id=1)
            )
        if not paciente4:
            data_nasci = datetime.strptime('26/10/1965', "%d/%m/%Y")
            ficha_de_atendimento.objects.create(
                nome_social = "Vanda Paulino Cerqueira",
                nome_completo = 'Vanda Paulino Cerqueira',
                nome_recepcionista = 'Dariuma',
                nome_mae = 'Alaíde',
                data_nascimento = data_nasci,
                bairro = Bairro.objects.get(id=9),

Atendimento/templates/Atendimento/cadastros_genericos/cadastros-genericos.html
{% extends 'global/template_geral.html' %}
{% load static %}
{% block title_login %}FILA DE TRIAGEM {% endblock title_login %}
{% block css %}
    <!--Css do Select2-->    
    <link rel="stylesheet" href=" {% static 'global/css/tabela-div.css' %}">
    <link rel="stylesheet" href=" {% static 'global/css/form.css' %}">
    <!--Tabela-->
    <link rel="stylesheet" href=" {% static 'global/css/tabela.css' %} "> 
{% endblock css %}    
{% block script %}
    <!--Script do Select2-->
<script>
    // In your Javascript (external .js resource or <script> tag)
$(document).ready(function() {
    $('#id_paciente_envio_triagem').select2();
});
</script>

{% endblock script %}
{% block body_title %}<i class="fa-solid fa-cash-register"></i> CADASTROS::. {% endblock body_title %}

{% block body_login %}


<!--uPDATE-->
{% if update_rua or update_bairro %}
 <div style='width:80%; margin:auto; text-align:center'>
    <h1 style=' text-align:left'><i class="fa-solid fa-pencil fa-bounce"></i> Atualização</h1>
</div> 
{% endif %}
 
 
 {% if cadas_rua %}
 <div style='width:80%; margin:auto; text-align:center'>
    <h1 style=' text-align:left'><i class="fa-solid fa-pencil fa-bounce"></i>Cadastra nome da rua</h1>
</div> 
 {% endif %}

{% if not listView %}
    {% if cadas_bairro %}
    <div style='width:80%; margin:auto; text-align:center'>
        <h1 style=' text-align:left'><i class="fa-solid fa-list"></i> Cadastro de Bairros</h1>
    </div>    
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_div}}
        <button type="submit"><i class="fa-regular fa-floppy-disk"></i> Salvar</button>
    </form>
    {% if cadas_rua %}
    <div> <a class='button-salvar' href="{% url 'Atendimento:list_rua' %}"><i class="fa-solid fa-list"></i>  Lista de Ruas </a> <a class='button-salvar' href="{% url 'Atendimento:registro-paciente' %}"><i class="fa-solid fa-bed"></i>  Cadastro de Pacientes</a> </div>
    {% endif %}
    {% if cadas_bairro %}
    <div> <a class='button-salvar' href="{% url 'Atendimento:list_bairro' %}"><i class="fa-solid fa-list"></i>  Lista de Bairros </a> <a class='button-salvar' href="{% url 'Atendimento:registro-paciente' %}"><i class="fa-solid fa-bed"></i>  Cadastro de Pacientes</a> </div>
    {% endif %}
    
{% endif %}
<div style='width:80%; margin:auto; text-align:center'>   
    
    {% if listView %} 
    {% if update_rua %}
        <h1 style=' text-align:left'><i class="fa-solid fa-list"></i>  Lista de Ruas</h1>
    {% endif %} 
    {% if update_bairro %}  
    <h1 style=' text-align:left'><i class="fa-solid fa-list"></i>  Lista de Bairros</h1>
    {% endif %}
        {% if page_obj.has_previous %}
        <a class="" href="?page={{page_obj.previous_page_number}}"><i class="fa-solid fa-angles-left"></i> Voltar</a>  
        {% endif %}
        {% if page_obj.has_next %}               
        <a href="?page={{ page_obj.next_page_number }}">Próxima página <i class="fa-solid fa-angles-right"></i></a>    
         {% endif %}
</div> 
    <table  class='Tabela-user' id="tabela-listar" border="0" cellpadding="0" cellspacing="0" width="60%">                
        <thead>
            <tr>
            <th class="top center"><strong>Nome</strong></td>
            <th class="top center" ><strong>Ação</strong></td>
            </tr>
        </thead>       
        <tbody>         
            {% for campo in  listView %}  
            <tr>
                {% if update_bairro %}
                    <td><a class="link-color" ><span>{{campo.bairro_nome}}</span></a></td>           
                    <td align="center">                        
                        <a href="{% url 'Atendimento:Update_bairro' campo.pk   %}" class="editar fa fa-check-circle" title="Editar"></a> 
                        <a href="{% url 'Atendimento:delete_bairro' campo.pk   %}" class="cancelar fa-solid fa-trash-can" title="Editar"></a>
                    </td>                
                {% endif %}
                {% if update_rua%}
                    <td><a class="link-color" ><span>{{campo.rua_nome}}</span></a></td>           
                    <td align="center">                        
                        <a href="{% url 'Atendimento:Update_rua' campo.pk   %}" class="editar fa fa-check-circle" title="Editar"></a> 
                        <a href="{% url 'Atendimento:delete_rua' campo.pk   %}" class="cancelar fa-solid fa-trash-can" title="Editar"></a>
                    </td>                
                {% endif %}
            </tr>       
            
            {% empty%}
                <tr>
                    <td colspan='7'>Nenhum registro informado</td>        
                </tr>                       
            {% endfor %}
        </tbody>                
    </table>    
                                 
<a class='button-salvar' href="{% url 'Atendimento:cadastra_bairro'%} "> Cadastrar <i class="fa-solid fa-plus fa-beat"></i></a>
{% endif %}
{% endblock body_login %}

Atendimento/templates/Atendimento/cadastros_genericos/delete.html
{% extends 'global/template_geral.html' %}
{% load static %}
{% block title_login %}FILA DE TRIAGEM {% endblock title_login %}
{% block css %}
    <!--Css do Select2-->    
    <link rel="stylesheet" href=" {% static 'global/css/form.css' %}">
    <!--Tabela-->
{% endblock css %}    
{% block script %}
    <!--Script do Select2-->
<script>
    // In your Javascript (external .js resource or <script> tag)
$(document).ready(function() {
    $('#id_paciente_envio_triagem').select2();
});
</script>

{% endblock script %}
{% block body_title %}<i class="cancelar fa-solid fa-trash-can"></i> EXCLUSÕES ::. {% endblock body_title %}



{% block body_login %}
<h1>Deseja excluir <b class='uppercase'>{{object_name}}</b></h1>
<form action="" method="post">
    {% csrf_token %}
    <div class="flex">
        {% if deleta_rua %}
        <a class="button-salvar" href="{% url 'Atendimento:list_rua' %}" type="submit">Cancelar</a>
        {% endif %}
        {% if deleta_bairro %}
        <a class="button-salvar" href="{% url 'Atendimento:list_bairro' %}" type="submit">Cancelar</a>
        {% endif %}
        <button class="button-cancelar" type="submit">Confirmar <i class="cancelar fa-solid fa-trash-can"></i></button>
    </div>
</form>





{% endblock body_login %}