Medicos/urls.py
from django.urls import path, re_path

from . import views

app_name = 'Medicos'

urlpatterns = [
    path('', views.medico_protuario_view_, name='medico_prontuario'),
    #path('', views.medico_prontuario_view.as_view(), name='medico_prontuario'),
    path('atendimento/<int:pk>', views.medico_atendimento_view, name='medico_atendimento'), 
    # Chama Paciente
    path('iniciar-atendimento/<int:pk>/', views.iniciar_atendimento_view, name='iniciar_atendimento'),
    path('medico_chama_paciente/<int:pk>/', views.MedicoChamaPacienteView.as_view(), name='medico_chama_paciente'),
    path('enfermeira_chama_paciente/<int:pk>/', views.EnfermeiroChamaPacienteView.as_view(), name='enfermagem_chama_paciente'),
    path('medico_avisa_atendimentoo/<int:pk>/', views.chamar_pacientee.update_chama_paciente.Update_chama_usuarioo, name='medico_avisa_pacientee'),
    path('enfermagem_avisa_atendimentoo/<int:pk>/', views.Update_chama_usuario_triagem, name='enfermagem_avisa_pacientee'),
    path('medico_avisa_atendimentoo/<int:pk>/', views.Update_chama_usuario_pos_atendimento, name='medico_avisa_paciente_pos_atendimento'),

    #perfil completo do paciente / historico
    path('medico/lista_historico_paciente/', views.paciente_lista_historico.as_view(), name='lista_paciente_medico'),  
    path('medico/historico_paciente/<int:pk>', views.paciente_perfil_completo, name='perfil_completo_paciente'),  
    path('medico/historico_paciente_historico/<int:pk>', views.paciente_perfil_completo_segunda_parte, name='perfil_completo_segunda_parte'),  
    path('medico/historico_paciente/historico/<int:pk>', views.paciente_perfil_completo_menu_lateral, name='perfil_completo_paciente_menu_lateral'),
    
    path('atendimento/paciente/<int:pk>', views.atendimento_medico_createView.as_view(), name='dados do paciente'),
    path('atendimento/paciente/update/<int:pk>', views.atendimento_medico_Atualiza.as_view(), name='dados_do_paciente_atualiza'),
    path('atendimento/paciente/medicamento/<int:pk>', views.atendimento_medico_updateview.as_view(), name='dados_do_paciente_medicamentos'),
    path('atendimento_medico_concluido/<int:pk>', views.atendimento_medico_concluido_update.as_view(), name='final_medico_concluida'),
    path('atendimento_medico_concluido/exibe/<int:pk>', views.exibe_prescreve_medicamento_update.as_view(), name='exibe_prescreve_medicamento'),
    # PDFs ------------------------------------------------------------------
    path('atendimento_medico_concluido/exibe/geraPDF/<int:pk>', views.gerarPdf, name='geraPdf'),
    # Cria, atualiza e apaga ----------------------------------------------------------------------
    path('medico_signup/', views.medico_signup, name='medico_signup'),
    path('medico_signup/atulizando/<int:pk>', views.MedicoUpdateView.as_view(), name='medico_signup_atualiza'),
    path('medico_signup/atulizando/extras/<int:pk>', views.MedicoUpdateView_extra.as_view(), name='medico_signup_atualiza_extras'),
    path('medico_signup/delete/<int:pk>', views.MedicoDeleteView.as_view(), name='medico_delete'),
    # Salas
    path('medicos/cadastroSalas/', views.Cadastra_Sala_view.as_view(), name='cadastroSala' ),
    path('medicos/Salas/', views.Lista_Salas_ListView.as_view(), name='salas' ),    
    path('medicos/Salas/atualizacao/<int:pk>', views.Atualiza_Sala_UpdatView.as_view(), name='salasUpdate' ),
    path('medicos/Salas/delete/<int:pk>', views.Delete_Sala_Delet.as_view(), name='salasDelete' ),
    # Exames
    path('medicos/cadastroExames/', views.Cadastra_Exame_view.as_view(), name='cadastroExame' ),    
    path('medicos/cadastroExames/atualizacao/<int:pk>', views.Atualiza_Exame_UpdatView.as_view(), name='exameUpdate' ),
    path('medicos/Salas/', views.Lista_Salas_ListView.as_view(), name='salas' ),    
    path('medicos/Exames/delete/<int:pk>', views.Delete_Exame_Delet.as_view(), name='exameDelete' ),

    # Medicamentos
    path('medicos/cdastraMedicamento/', views.Cadastra_Medicamento.as_view(), name='cadastroMedicamento' ),    
    path('medicos/cadastroExames/atualizacao/<int:pk>', views.Atualiza_Exame_UpdatView.as_view(), name='exameUpdate' ),
    path('medicos/Salas/', views.Lista_Salas_ListView.as_view(), name='salas' ),    
    path('medicos/Exames/delete/<int:pk>', views.Delete_Exame_Delet.as_view(), name='exameDelete' ),
    # vincula Profissional
    path('medicos/Salas/profissional/', views.VinculaProfissiona_sala_view.as_view(), name='salasProfissionalCreate' ),
    path('medicos/Salas/profissional/update/<int:pk>', views.VinculaProfissiona_sala_update.as_view(), name='salasProfissionalUpdate' ),
    path('medicos/Salas/profissional/delete/<int:pk>', views.DeleteProfissionaSala_Delet.as_view(), name='salasProfissionalDelete' ),
  
    path('cadastrar-chamada/', views.cadastrar_chamada, name='cadastrar_chamada'),
    # importar csv para cid 10
    path('importar_csv/', views.import_csv, name='importa_csv'),
     # Paciente não atendeu ao chamdo
    path('medico/chama_paciente/n_atende/<int:pk>', views.medico_paciente_nao_atende, name='medio_n_atendeu'),
    # Conlclui todos atendimentos em aberto
    path('medico/chama_paciente/conclui_all/', views.conclui_all, name='conclui_atend'),
    # Atualizar o campo relatorio de Medico atendimento para True
    path('medico/imprime/<int:pk>', views.atualizar_relatorio, name='atualiza_relatorio')

]

upa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import path, re_path
from configUPA.views import handler404, handler500

from django.shortcuts import render  # Importe render

def handler500(request, *args, **kwargs):
    context = {'error_message': 'Oops! Houve um erro interno no servidor.'}
    return render(request, 'configUPA/error-500.html', context, status=500)


urlpatterns = [
    path('admin/', admin.site.urls),
    #Django_select2
    #Atendimento de emergencia
    path('', include('Access_Login.urls')),
    path('atendimento/', include('Atendimento.urls')),
    path('triagem/', include('Triagem.urls')),
    path('medicos/', include('Medicos.urls')),
    path('configura/', include('configUPA.urls')),
    path('imprime/', include('PrintPDFs.urls')),
    re_path(r'^.*/$', handler404),
    re_path(r'^.*/500/$', handler500),
]

handler500 = 'configUPA.views.handler500'

Medicos/forms.py
from django import forms
from Triagem.models import triagem, Exames_Model

class Form_medico_atendimento (forms.Form):

    paciente_triagem = forms.CharField(max_length=2, required=False, help_text='Nome do paciente')    
    pressao_arterial_PA = forms.CharField(help_text='Pressão arterial do paciente')
    frequencia_cardiaca_FC = forms.CharField(help_text='Frequencia Cardiaca do Paciente')
    frequencia_respiratoria_FR = forms.CharField(help_text='')
    saturacao_de_oxigenio_SPO2 = forms.CharField(help_text='')
    hemoglicoteste_HGT = forms.CharField(help_text='')
    temperatura_TEMP = forms.CharField(help_text='')
    peso = forms.CharField(help_text='')
    data_triagem = forms.CharField(help_text='')
    hora_triagem = forms.CharField(help_text='')
    classifica_tipo = forms.CharField(help_text='')
    observacao = forms.Textarea()
    final_triagem = forms.CharField(help_text='')
    final_triagem_time = forms.DateField(help_text='')


class Prescreve_Medicamentos_fomr(forms.ModelForm):
    exames = forms.ModelMultipleChoiceField(queryset=Exames_Model.objects.all(), widget=forms.SelectMultiple, required=False)

    class Meta:
        model = triagem
        fields = ['exames', 'atestado', 'preescrever_medicamento_medico']
        labels = {}
        widgets = {
            'atestado': forms.NumberInput(attrs={'type': 'range', 'min': 0, 'max': 30, 'step': 1, 'oninput': 'updateTextInput(this.value)'}),
        }


class ChamarPacienteForm(forms.Form):
    class Meta:
        fields = ['nome_paciente','profissionalSaude_id']
        
    nome_paciente = forms.CharField(widget=forms.HiddenInput())
    profissionalSaude_id = forms.CharField(widget=forms.HiddenInput())




       

Medicos/views/a_aguardando_atendimento.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from Atendimento.models import *
from Triagem.models import triagem
from django.contrib.auth.hashers import make_password
from Triagem.models import Atendimento_especializado
from Medicos.models import Medico_atendimento
from datetime import datetime


@login_required
def medico_protuario_view_(request):
    busca_paciente = request.GET.get('busca_paciente')
    nao_finalizado = []
    if busca_paciente:
        triagem_filtro = triagem.objects.exclude(final_medico_atendimento=1) and triagem.objects.filter(paciente_triagem__paciente_envio_triagem__nome_social__icontains = busca_paciente)    
        checked = 'checked'
    else:
        triagem_filtro = triagem.objects.exclude(final_medico_atendimento=1)
        checked = ''
    triage_all = triagem.objects.all()

    for ated_espec in triage_all:
        
        try:
            nao_finalizado.append(ated_espec.medico_atendimento.paciente_medico_atendimento.final_medico_atendimento)
            
        except Medico_atendimento.DoesNotExist:
            pass
    
    return render(request, 'Medicos/medico.html', {
        'object_list': triagem.objects.exclude(final_medico_atendimento=1),
        'atendimento_especi': Atendimento_especializado.objects.all(),
        'atendimentos_hoje': Medico_atendimento.objects.filter(data_medico=datetime.now()),
        'atend_aguarda_final': triagem_filtro,
        'checked5' : checked,
        'nao_finalizado': nao_finalizado,    
    })
    

Medicos/views/b_info_vindo_triagem.py
from django.contrib.auth.decorators import login_required
from Atendimento.models import *
from Triagem.models import triagem
from django.shortcuts import  render

@login_required
def medico_atendimento_view(request, pk):
    dados_triagem = triagem.objects.filter(pk=pk)
    for dados in dados_triagem:
        #tempo1 =datetime(dados.hora_triagem)
        dados = dados.paciente_triagem_id        
        dados_triagem = envio_triagem.objects.filter(pk=dados) 
        info_Hora_Tri = triagem.objects.filter(paciente_triagem_id=dados)
        for t in info_Hora_Tri:
            info_Hora_envioT = t.hora_triagem     

    dados_envio_triagem = envio_triagem.objects.filter(pk=dados)
    for dados in dados_envio_triagem:
        #tempo2 =time(dados.horario_triagem)
        dados = dados.paciente_envio_triagem_id 
        info_Hora_envioT = envio_triagem.objects.filter(paciente_envio_triagem_id = dados)
        for t in info_Hora_envioT:
            info_Hora_envioT = t.horario_triagem

    #contem o horário da triagem
    info_Hora_envioT

    #contem o horário do envio_triagem
    info_Hora_envioT   
        
    return render(request, 'Medicos/medico_atendimento.html', {
        'paciente_triagem' : triagem.objects.filter(pk=pk), 
        'ficha_atendimento' : ficha_de_atendimento.objects.filter(pk=dados),
        'dados_triagem' : dados_triagem,
        #'tempo' : tempo         
    } )

Medicos/views/c_Update_atendimento_Paciente.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.models import Group
from django.http import  HttpResponseRedirect
from django.urls import reverse
from django.views.generic import UpdateView
#from Medicos.forms import Form_medico_atendimento
from Medicos.models import CustomUser, Medico_atendimento
from Triagem.models import triagem
from Medicos.models import CustomUser


class atendimento_medico_Atualiza(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Medico_atendimento
    #Chave Estrangeira 'paciente_medico_atendimento'
    fields = ['paciente_medico_atendimento', 'historico_doenca_atual_HDA', 'exame_fisico', 'Diagnostico', 'conduta','classificacao_internacional_doenca_CID']
    template_name = 'Medicos/medico_atendimento_atendimento.html'   
    success_message = 'Avaliação médica feita com sucesso'
     
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) 
        pk = self.kwargs['pk']    
        trigem_id = Medico_atendimento.objects.get(pk=self.kwargs['pk'])        
        context['triagem'] = triagem.objects.filter(id = trigem_id.paciente_medico_atendimento.id)
        context['atendimento'] = 'atendimento'       

        return context
    
    #success_url = reverse_lazy('Medicos:dados do paciente_medicamentos self.kwargs['pk']')
    def get_success_url(self):
        return reverse('Medicos:dados_do_paciente_medicamentos', kwargs={'pk':self.object.paciente_medico_atendimento.id})
    
    
    

Medicos/views/c_atendimento_Paciente.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import Group
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.http import  HttpResponseRedirect
from django.urls import reverse
from django.views.generic import CreateView
from Medicos.models import CustomUser, Medico_atendimento, Chamar_P_para_atendimento
from Triagem.models import triagem
from datetime import datetime


class atendimento_medico_createView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Medico_atendimento
    #Chave Estrangeira 'paciente_medico_atendimento'
    fields = ['paciente_medico_atendimento', 'historico_doenca_atual_HDA', 'exame_fisico', 'Diagnostico','medicamento', 'conduta','classificacao_internacional_doenca_CID']
    template_name = 'Medicos/medico_atendimento_atendimento.html'   
    success_message = 'Avaliação médica feita com sucesso'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) 
        pk = self.kwargs['pk']  
    
        # Evitar Erros
        exibe_b = {}
        exibe_id = None
        try:
            # Usar o método first() para pegar o primeiro registro
            chamado = Chamar_P_para_atendimento.objects.filter(nome_paciente=pk, data_chamada__date=datetime.now().date()).first()
            exibe_b = chamado.chamado
            exibe_id = chamado.pk

        except AttributeError:
            messages.add_message(self.request, messages.DEBUG, f"Nenhuma chamada foi encontrada para o paciente {self.kwargs['pk']} na data de hoje")
     
        if exibe_b:
            pass
        else:
            chamado = False
            exibe_b = False
           
        context['triagem'] = triagem.objects.filter(id = pk)
        context['chamado'] = chamado
        context['exibe_b'] = exibe_b  
        context['atendimento'] = 'atendimento'     
        context['exibe_id'] = exibe_id              
        return context
    
    def form_valid(self, form):
        self.object = form.save(commit=False)
        
        # Define os campos do objeto Medico_atendimento
        self.object.paciente_medico_atendimento_id = self.kwargs['pk']        
        
        medico_id = self.request.user.id
        medico_group_id = None 
        medico_group = CustomUser.objects.filter(user_id=medico_id)
        
        for med in medico_group:
            medico_group_id = med.grupo_id
            crm = med.crm
            print(f'esse é o crm do medio {crm}{medico_group}')        
        medico_group = Group.objects.filter(id=medico_group_id)
        
        for med in medico_group:
            medico_group = med.name
            
            if medico_group == "group_Medicos":
                self.object.medico_nome = f'{self.request.user.first_name} {self.request.user.last_name} | CRM nº {crm}'
            else:
                self.object.medico_nome = self.request.user.username        
        self.object.paciente_medico_atendimento = True
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())
    
    def get_success_url(self):        
        return reverse('Medicos:dados_do_paciente_medicamentos', kwargs={'pk':self.kwargs['pk']})

Medicos/views/d_atestados_exames.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import  UpdateView
from Triagem.models import triagem
from Medicos.models import Medico_atendimento
from Atendimento.models import *
from Triagem.models import triagem
from django.contrib.auth.mixins import LoginRequiredMixin
from Medicos.forms import Prescreve_Medicamentos_fomr


# -------------------------- PREESCRIÇÃO DE EXAMES, MEDICAMENTOS, ATESTADOS ---------------------------------------------------------
class atendimento_medico_updateview(LoginRequiredMixin, UpdateView):
    model = triagem 
    #fields = ['exames', 'atestado']
    form_class = Prescreve_Medicamentos_fomr
    template_name = 'Medicos/prescrever-medicamento.html'
    
    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto['pk'] = self.kwargs['pk']
        contexto['resultado_medico'] = Medico_atendimento.objects.filter(paciente_medico_atendimento_id = self.kwargs['pk'])
        return contexto

    def get_success_url(self):
        envio_filter = self.kwargs['pk']
        triagem_filter = triagem.objects.filter(id = envio_filter)
        for n in triagem_filter:
            key = n.id
            data_key = n.data_triagem   

        return reverse('Medicos:exibe_prescreve_medicamento', kwargs={'pk':key})     
        

Medicos/templates/Medicos/confirma_final.html
{% extends 'global/template_geral.html' %}
{% block css %}
{% load static %}
<link rel="stylesheet" href="{% static 'global/tabela/css/style.css' %}">
<link rel="stylesheet" href="{% static 'global/css/menu/menu.giro.css' %}">
<link rel="stylesheet" href="{% static 'global/css/formularios.css' %}">

<style> {% for dados in paciente_triagem  %} 
              {% if dados.classifica_tipo.id == 1 %}
              .dados-preatendimento ul li span{
                     color: #AA0000;
                     font-size: 1.3rem;
              }
              {% elif dados.classifica_tipo.id == 2  %}
              .dados-preatendimento ul li span{
                     color: #ff6600;
                     font-size: 1.3rem;
              {% elif dados.classifica_tipo.id == 3  %}
              .dados-preatendimento ul li span{
                     color:  #008200;
                     font-size: 1.3rem;
              {% elif dados.classifica_tipo.id == 4  %}
              .dados-preatendimento ul li span{
                     color: #008dc0;
                     font-size: 1.3rem;
              {% endif %}  
       {% endfor %}     
       #id_final_medico_atendimento {
              scale: 0.8 !important;
       }
</style>

{% endblock css %}  
<!--Imagem Representando o setor-->
{% block vetor-img-aereo %}<img src=" {% static 'home/doctor.fw.png' %} " alt="">{% endblock vetor-img-aereo %}
<!--END Imagem Representando o setor-->
{% block title_login %}ÁREA MÉDICA {% endblock title_login %}
{% block titulo_ %} 
       ÁREA MÉDICA - Paciente: {{triagem}}

{% endblock titulo_ %} 
{% block body_title %}
       ÁREA MÉDICA - Paciente: {{triagem}}
{% endblock body_title %}
{% block body_login %}
<div  class='dados-preatendimento'>       
       <p>&nbsp:</p>
       <h1>Final de Atendimento</h1>
       <hr>
       <form method='POST' >
              {% csrf_token %}              
              <div class='bg-body-tertiary shadow-sm p-3 text-center w-75'> 
                     <label  for="id_final_triagem">
                            Completado o atendimento ao paciente <strong class='text-uppercase'>{{triagem}}</strong>, 
                            confirmo que todos os procedimentos necessários foram realizados de acordo com os padrões estabelecidos.
                             O paciente foi devidamente assistido e encontra-se pronto para seguir sua próxima etapa de cuidados médicos, se necessário.
                            
                     </label>
                     <div class='m-2 p-2 btn btn-secondary'>Clique no quadrado à direita para confirmar: 
                     <input  style="scale:5" type="checkbox" name="final_medico_atendimento" value="1" maxlength="3" required="" id="id_final_medico_atendimento"> 
                      </div>                             
              </div> 
              <div class='w-75 m-5'>
                     <div>
                            <p><strong>Observação:</strong></p>
                            <p>
                                Após confirmar a conclusão do atendimento ao paciente {{triagem}}, o nome deste paciente será removido da seção 
                                <strong>Pacientes Aguardando Atendimento</strong>.
                            </p>
                            <p>
                                Para reintegrar o nome do paciente à lista de espera, será necessário que ele passe novamente pela 
                                <strong>Fila de Espera</strong> e, em seguida, pela <strong>Classificação</strong>.
                            </p>
                        </div>
                        
                     <button class='btn btn-sm btn-primary w-75 m-auto' type="submit">Finalizar atendimento</button>
              </div>
              
              
       </form>       
</div>
{% endblock body_login %}

Medicos/templates/Medicos/medico_atendimento.html
{% extends 'global/template_geral.html' %}
{% block css %}
{% load static %}
<link rel="stylesheet" href="{% static 'global/tabela/css/style.css' %}">

<style> {% for dados in paciente_triagem  %} 
              {% if dados.classifica_tipo.classifica_tipo == "Vermelho" %}
              .dados-preatendimento ul li span{
                     color: #AA0000;
                     font-size: 1.3rem;
              }
              {% elif dados.classifica_tipo.classifica_tipo == "Laranja"   %}
              .dados-preatendimento ul li span{
                     color: #ff6600;
                     font-size: 1.3rem;
              {% elif dados.classifica_tipo.classifica_tipo == "Verde"  %}
              .dados-preatendimento ul li span{
                     color:  #008200;
                     font-size: 1.3rem;
              {% elif dados.classifica_tipo.classifica_tipo == "Azul" %}
              .dados-preatendimento ul li span{
                     color: #008dc0;
                     font-size: 1.3rem;
              {% endif %}  
       {% endfor %}  
       
       .style_triagem ul {
              font-size:0.9rem;
              margin-left:2.5rem }
      
</style>
{% endblock css %}  
{% block title_login %}ÁREA MÉDICA {% endblock title_login %}
{% block titulo_ %} 
       ÁREA MÉDICA - Paciente:
       {% for dados in ficha_atendimento  %}       
              {{dados.nome_social}}
       {% endfor %}
{% endblock titulo_ %} 
{% block body_title %}
       ÁREA MÉDICA - Paciente:
       {% for dados in ficha_atendimento  %}       
              {{dados.nome_social}}
       {% endfor %}
{% endblock body_title %}
{% block body_login %}
<div class='dados-preatendimento'>{% for dados in paciente_triagem  %}     
       {% for dados_registro in ficha_atendimento  %}     
              <div class="info-triagem 
                     {% if dados.classifica_tipo.classifica_tipo == 'Vermelho' %}
                            prosseguir-red
                     {% elif dados.classifica_tipo.classifica_tipo == 'Laranja'  %}
                            prosseguir-laranja
                     {% elif dados.classifica_tipo.classifica_tipo == 'Verde'  %}
                            prosseguir-green                                            
                     {% elif dados.classifica_tipo.classifica_tipo == 'Azul'  %}
                            prosseguir-azul
                     {% endif %}      
              ">
              CLASSIFICAÇÃO DE RISCO <span class='text-uppercase'>{{dados.classifica_tipo}} </span> 
              </div>
              <p class='fs-5'><i class="fa-regular fa-calendar-check"></i>&nbsp;{{dados.data_triagem}} &nbsp; | &nbsp; <i class="fa-solid fa-clock"></i>&nbsp;{{dados.hora_triagem}} &nbsp; | &nbsp; Informações sobre a classificação do paciente: <b class='uppercase'>{{dados_registro.nome_social}} </b></p>
              <hr>
              <div class='style_triagem '>
                     <div class='row row-cols-4'>
                     <ul class='col-2 px-5'>
                            <li class='fs-7'><b>Nome Completo:</b> <p class='uppercase'><span> {{dados_registro.nome_social}} </span></p></li>                            
                            <li class='fs-7'><b>Pressão Arterial Sistólica:</b><p> <span> {{dados.pressao_arterial_PA}} mmHg</span></p></li>
                            <li class='fs-7'><b>Pressão Arterial Diastólica:</b><p> <span> {{dados.pressao_arterial_PA_2}} mmHg</span></p></li>
                     </ul>
                     <ul class='col-3 px-5'>
                            <li class='fs-7'><b>FC - Frequência Cardiaca:</b><p><span> {{dados.frequencia_cardiaca_FC}} bpm</span></p></li>
                            <li class='fs-7'><b>FR - Frequencia Respiratoria:</b><p><span> {{dados.frequencia_respiratoria_FR}} bpm </span></p></li>     
                            <li class='fs-7'><b>SPO² - Saturação de Oxigênio :</b><p> <span> {{dados.saturacao_de_oxigenio_SPO2}}% </span> </p></li> 
                     </ul>
                     <ul class='col-2'>   
                            <li class='fs-7'><b>HGT - Hemigloteste :</b><p><span> {{dados.hemoglicoteste_HGT}} mg/dL </span></p></li>
                            <li class='fs-7'><b>TEMP - Temperatura:</b><p> <span> {{dados.temperatura_TEMP}} °C </span></p></li></p>                        
                            <li class='fs-7'><b>Peso:</b><p> <span> {{dados.peso}} kg</span></p></li>                            
                     </ul>
                     <ul class='col-3'>
                            <li class='fs-7'><b>Data do atendimento:</b><p><span> {{dados.data_triagem}} </span> </p></li>
                            <li class='fs-7'>TEMPO DE ESPERA:
                                   <ul>
                                          {% for envio_triagem in dados_triagem %}
                                                 <li><b>Horário em que o paciente passou pela recepção:</b><p><span> 
                                                        {{envio_triagem.horario_triagem}} Hm
                                                        </span></p></li>
                                                 <li><b>Horário em que o paciente foi chamado para a triagem:</b><p><span> {{dados.hora_triagem}} Hm </span></p></li>
                                                 {% comment "" %}<li><b>Tempo de espera do paciente até o atendimento:</b><span> {{tempo}} </span></li>{% endcomment %}
                                          {% endfor %}
                                   </ul>
                            </li> 
                     </ul>                  
                     
                     </div>
                     <div class="row">
                            <div class='col fs-6  m-1 p-1 '>
                                   <p class="border-bottom border-black">Classificação de risco atual desse paciente:</p>
                                   <p> <span class='fs-4'> {{dados.classifica_tipo}}  </span></p></div>  
                            <div class='col fs-6  m-1 p-1'><p class="border-bottom border-black">Enfermeira responsável pelo Atendimento:</p><p> <span class='fs-4'>{{dados.nome_da_enfermeira}}</span></p></div>  
                     </div>
                     <div class='fs-6'><p class="">Sitomas relatados pelo paciente durante a triagem: </b>
                            <div style='font-size: 1.3rem; padding: 1.4rem; ' class="bg-light-subtle">
                                   {{dados.observacao|safe}}
                            </div>                            
                     </div> 
                     {% if  dados.paciente_triagem.paciente_envio_triagem.alergias == '1' %} 
								<div class='fs-7 m-2 bg-danger-subtle p-2 h-auto rounded-1'>Paciente Alérgico:
                                                               <div class='ml-3 p-2  w-100 fs-5'>
                                                                             {{dados.paciente_triagem.paciente_envio_triagem.conteudo_alergia}}                          
                                                               </div>
								</div>
						{% endif %} 
						{% if dados.data_triagem.paciente_envio_triagem.comorbidades == '1'  %} 
								<div class='fs-7 m-2 bg-danger-subtle p-2 h-auto rounded-1'>Comorbidades:
                                                               <div class='ml-3 p-2  w-100 fs-5'>
                                                                             {{dados.paciente_triagem.paciente_envio_triagem.conteudo_comorbidades}} 
                                                               </div> 
								</div>
						{% endif %} 
              </div>

       {% endfor %}
       <hr>
       <a style='text-align: center' href="{% url 'Medicos:iniciar_atendimento' dados.pk %}"> {{dados.paciente_envio_triagem_id}} <span class='prosseguir 
              {% if dados.classifica_tipo.classifica_tipo == "Vermelho" %}
              prosseguir-red
              {% elif dados.classifica_tipo.classifica_tipo == "Laranja"  %}
              prosseguir-laranja
              {% elif dados.classifica_tipo.classifica_tipo == "Verde"  %}
              prosseguir-green                                            
              {% elif dados.classifica_tipo.classifica_tipo == "Azul"  %}
              prosseguir-azul
          {% endif %}'> Iniciar o atendimento <i class="fa-regular fa-paper-plane"></i> </span></a>
          {% endfor %}
</div>
{% endblock body_login %}